project:
  title: "Research Project for SOC 513"
  output-dir: _products
  execute-dir: project
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.ts   # remove previously constructed files
  render:
    # if analysis is split into multiple docs, add them here
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    - "!bibliography/"

author:
  - name: Amit Das
    orcid: 0000-0003-1123-8455
    email: amitdas@uoregon.edu
    url: https://business.uoregon.edu/directory/management/all/amitdas
    attributes:
      corresponding: true
    affiliations:
      - id: uo
        name: University of Oregon
        department: Management
        address: Anstett 291A
        city: Eugene
        region: OR
        country: USA
        postal-code: 97405
  
execute: 
  freeze: false
  
editor: source



